### ISSUE TITLE
Where to put script and open what console :

### ISSUE THREAD

**Issue by EManEYes** [mirage2032/Scrap.tf-RaffleBot#3]
You said you have to open the console and save the cookies with /save but what console, and what script?
Would be nice if you explain

**Comment by mirage2032** [comment]
The script is very outdated, as I am very bored I will update.
Doing this just for you xD
The new one is going to be more user friendly, will be done in 1-2 days.

**Comment by EManEYes** [comment]
I use Windows 10, I use Google chrome Tampermonkey A Userscript extension, the script only scrolls down. And doesn't do anything else.
Thanks, for updating and replying.

**Comment by EManEYes** [comment]
I use Windows 10, If you want me to awnser that.

**Comment by mirage2032** [comment]
almost done, just a few problems witch captcha. Won't take much more

**Comment by mirage2032** [comment]
Just finished rewriting it. Try it when you got the time.

I will be waiting for feedback :)

**Comment by kkgamer18** [comment]
How to install bs4 and Selenium?
When i launch the .py file nothing happens

**Comment by mirage2032** [comment]
Install Python from the link below
https://www.python.org/downloads/
Make sure that "Add Python 3.X to path" is checked
![](https://datatofish.com/wp-content/uploads/2018/10/0001_add_Python_to_Path.png)
Go to CMD and write the following lines
`pip install selenium
pip install bs4`
execute RUN.bat, just added it

**Comment by kkgamer18** [comment]
cant get it to work man

**Comment by kkgamer18** [comment]
'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kkgamer18** [comment]
add python to path option aint there

**Comment by mirage2032** [comment]
try completely uninstalling python then reinstalling it.
You should have the path option afterwards.

**Comment by kkgamer18** [comment]
Ok, I will reinstall it

**Comment by mirage2032** [comment]
I'll be waiting fo an update

**Comment by kkgamer18** [comment]
yo its working good job mate

**Comment by kkgamer18** [comment]
love ya

**Comment by mirage2032** [comment]
Good to hear that. I will continue updating it.
There are still featues that need to be added, a user interface wuld definetly help, also a continuous mode so it keeps entering raffles nonstop.
If you got any feature ideeas just tell me and i might add them.

**Comment by EManEYes** [comment]
Well, I have no other feature in mind . But it would be cool if you added some sort of AUTO-TRADE feature like trading USELESS weapons away.

**Comment by mirage2032** [comment]
I will look on how i can be done.
It will be not that easy as I will have to program a trade bot.
That will mean having to deal wth steam directly and getting the steam autehnticator codes on pc.

**Comment by EManEYes** [comment]
Yeah, If you can't do that or you have not enough of time for it it's okay.

**Comment by EManEYes** [comment]
Would be great if you can make an Tutorial (VIDEO) aswell.

**Comment by mirage2032** [comment]
I will keep updating the script when i got the time.

I am still learning to code and doing projects like this helps me.

**Comment by kkgamer18** [comment]
See, try to do this - Don't quit the script if you have joined all the raffles, instead keep it running and if someone creates a raffle join it automatically.
And you can also try and do something of the puzzle raffles because a friend of mine said that he once created a script to join puzzle raffles without code or something like hat. Try if you can its just an idea.
Good Luck

**Comment by kkgamer18** [comment]
hey mate, sccript stopped working

**Comment by mirage2032** [comment]
I will check later today if i got the time.
At the momment I have a dayjob and doing webcrawling freelancer work so time is limited.

**Comment by kkgamer18** [comment]
alright mate

**Comment by mirage2032** [comment]
Didn't check the script yet but i think I might now something that'll work.
Try deleting cookie.pkl and run the script.
It's going to ask you to login again.
